// <auto-generated />
using System;
using BlazorChallengeApp.Server.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorChallengeApp.Server.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20220713070053_ChangedBoookingModel")]
    partial class ChangedBoookingModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("BlazorChallengeApp.Shared.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("BlazorChallengeApp.Shared.Movie", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cast")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RunningTimesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunningTimesId");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("BlazorChallengeApp.Shared.RunningTimes", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sun")
                        .HasColumnType("TEXT");

                    b.Property<string>("Thu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Wed")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RunningTimes");
                });

            modelBuilder.Entity("BlazorChallengeApp.Shared.Seat", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("TEXT");

                    b.Property<int>("column")
                        .HasColumnType("INTEGER");

                    b.Property<int>("row")
                        .HasColumnType("INTEGER");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("BookingId");

                    b.ToTable("Seat");
                });

            modelBuilder.Entity("BlazorChallengeApp.Shared.Ticket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("_price")
                        .HasColumnType("REAL");

                    b.Property<string>("_ticketName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ticket");

                    b.HasData(
                        new
                        {
                            Id = "3bb624cd-50c8-4227-bcce-f99061259819",
                            _price = 10.0,
                            _ticketName = "ADULT"
                        },
                        new
                        {
                            Id = "8a007cac-c7c7-4b1f-97f2-efd5aa65c4f0",
                            _price = 10.0,
                            _ticketName = "CHILD (AGE 14 AND UNDER)"
                        },
                        new
                        {
                            Id = "eac31e45-3064-4a86-ae52-3a4947a74241",
                            _price = 32.0,
                            _ticketName = "FAMILY X 4(2 AD + 2CH OR 1AD +3 CH)"
                        },
                        new
                        {
                            Id = "59e277de-c3fc-4c9c-84e9-ded3c6b36377",
                            _price = 8.5,
                            _ticketName = "STUDENT"
                        },
                        new
                        {
                            Id = "0c6614ba-f633-4462-a05f-28c283997b34",
                            _price = 8.5,
                            _ticketName = "SENIOR(65 & OVER)"
                        });
                });

            modelBuilder.Entity("BlazorChallengeApp.Shared.Movie", b =>
                {
                    b.HasOne("BlazorChallengeApp.Shared.RunningTimes", "RunningTimes")
                        .WithMany()
                        .HasForeignKey("RunningTimesId");

                    b.Navigation("RunningTimes");
                });

            modelBuilder.Entity("BlazorChallengeApp.Shared.Seat", b =>
                {
                    b.HasOne("BlazorChallengeApp.Shared.Booking", null)
                        .WithMany("seats")
                        .HasForeignKey("BookingId");
                });

            modelBuilder.Entity("BlazorChallengeApp.Shared.Booking", b =>
                {
                    b.Navigation("seats");
                });
#pragma warning restore 612, 618
        }
    }
}
